Remove story embed API usage
prezly/theme-nextjs-bea pull request #129
Opened 2022-05-04 07:37 UTC by aspirisen

2022-05-05 07:47 UTC, oleg-semyonov commented on components/SlateRenderer/components/StoryBookmark.tsx
> +    const storyOEmbedInfo = story?.referenced_entities?.stories?.[node.story.uuid];
Linter complains for a reason :)
Let's call it `referencedStory` for simplicity

2022-05-05 07:47 UTC, oleg-semyonov commented on components/SlateRenderer/components/StoryBookmark.tsx
> +    const storyOEmbedInfo = story?.referenced_entities?.stories?.[node.story.uuid];
Also, was this API there before we implemented the embed stories API? 🤔

2022-05-12 09:37 UTC, oleg-semyonov commented on package.json
> +    "@prezly/story-content-format": "^0.55.4",
I see you've added the new `story-content-format` package. Since it replaces `slate-types`, can we get rid of it in scope of this PR?

2022-05-12 09:37 UTC, e1himself requested changes

2022-05-12 09:50 UTC, aspirisen commented on package.json
> +    "@prezly/slate-types": "^0.36.0",
Where can i find these consts https://github.com/prezly/theme-nextjs-bea/blob/main/components/RichText/List.tsx#L2 ?

2022-05-12 14:37 UTC, merged